# Generated by Django 4.0.3 on 2022-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
