# Generated by Django 4.0.3 on 2022-04-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_slug_alter_todo_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
